import React from 'react';
import {
    ComposedChart,
    Area,
    XAxis,
    YAxis,
    CartesianGrid,
    ResponsiveContainer,
    Line,
    Legend
} from 'recharts';

// Reusing types from parent (or importing if moved to separate file)
type ReportProps = {
    chartData: any[]; // The calculated chart data points
    product: any; // Selected product details
    modalityName: string; // Active modality name
    fluorophores: any[]; // Active fluorophores for legend/metrics
    dichroics: any[]; // Active dichroics
    emissionFilters: any[]; // All active filters
    imagingSplitters: any[]; // Active splitters
    cam1FilterId: string;
    cam2FilterId: string;
    minWavelength: number;
    maxWavelength: number;
    efficiencyMetrics: {
        dyeName: string;
        color: string;
        cam1: string; // formatted percentage
        cam2?: string;
        splitRatio?: string;
    }[];
};

export const SpectraReport = React.forwardRef<HTMLDivElement, ReportProps>(({
    chartData,
    product,
    modalityName,
    fluorophores,
    dichroics,
    emissionFilters,
    imagingSplitters,
    cam1FilterId,
    cam2FilterId,
    minWavelength,
    maxWavelength,
    efficiencyMetrics
}, ref) => {

    // Resolving Filter Names
    const cam1FilterName = emissionFilters.find(f => f.id === cam1FilterId)?.name || 'None';
    const cam2FilterName = emissionFilters.find(f => f.id === cam2FilterId)?.name || 'None';

    const isDual = (product?.name || '').includes('M90') || (product?.name || '').includes('MN360');

    return (
        <div
            ref={ref}
            className="w-[1000px] bg-white p-8 flex flex-col gap-6 text-black font-sans"
        // Style removed: positioning is now handled by the parent container in SpectraChart.tsx
        >
            {/* Header: Title & Logo/Product */}
            <div className="flex justify-between items-start border-b border-gray-200 pb-6">
                <div>
                    <h1 className="text-3xl font-bold text-gray-900 mb-2">Spectra Configuration Report</h1>
                    <p className="text-gray-500 text-sm">Generated by Abbelight Academy Spectra Viewer</p>
                    <p className="text-gray-400 text-xs mt-1">{new Date().toLocaleDateString()} {new Date().toLocaleTimeString()}</p>
                </div>
                {product?.image_url && (
                    <div className="flex flex-col items-end">
                        <img
                            src={product.image_url}
                            alt={product.name}
                            className="h-24 object-contain mb-2"
                        />
                        <span className="font-bold text-lg text-primary">{product.name}</span>
                    </div>
                )}
            </div>

            {/* Configuration Summary Grid */}
            <div className="grid grid-cols-2 gap-8 bg-gray-50 p-6 rounded-xl border border-gray-100">
                <div className="space-y-3">
                    <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider border-b border-gray-200 pb-1 mb-2">System Setup</h3>
                    <div className="flex justify-between">
                        <span className="text-gray-600 font-medium">Product Base:</span>
                        <span className="font-semibold">{product?.name || 'Unknown'}</span>
                    </div>
                    <div className="flex justify-between">
                        <span className="text-gray-600 font-medium">Imaging Modality:</span>
                        <span className="font-semibold">{modalityName || 'Custom'}</span>
                    </div>
                    <div className="flex justify-between">
                        <span className="text-gray-600 font-medium">Wavelength Range:</span>
                        <span className="font-mono text-sm">{minWavelength}nm - {maxWavelength}nm</span>
                    </div>
                </div>

                <div className="space-y-3">
                    <h3 className="text-sm font-bold text-gray-400 uppercase tracking-wider border-b border-gray-200 pb-1 mb-2">Optical Path</h3>
                    <div className="flex justify-between items-center">
                        <span className="text-gray-600 font-medium">Camera T Filter:</span>
                        <span className="font-semibold bg-white border px-2 py-0.5 rounded text-sm">{cam1FilterName}</span>
                    </div>
                    {isDual && (
                        <div className="flex justify-between items-center">
                            <span className="text-gray-600 font-medium">Camera R Filter:</span>
                            <span className="font-semibold bg-white border px-2 py-0.5 rounded text-sm">{cam2FilterName}</span>
                        </div>
                    )}
                    {dichroics.filter(d => d.visible).length > 0 && (
                        <div className="flex flex-col gap-1 mt-2">
                            <span className="text-gray-600 font-medium text-sm">Active Dichroics:</span>
                            <div className="flex flex-wrap gap-1">
                                {dichroics.filter(d => d.visible).map((d: any) => (
                                    <span key={d.id} className="text-xs bg-gray-200 px-1.5 py-0.5 rounded text-gray-700">{d.name}</span>
                                ))}
                            </div>
                        </div>
                    )}
                </div>
            </div>

            {/* Main Chart Area */}
            <div className="w-full h-[500px] border border-gray-200 rounded-xl p-4 bg-white">
                <ResponsiveContainer width="100%" height="100%">
                    <ComposedChart
                        data={chartData}
                        margin={{ top: 10, right: 10, left: 10, bottom: 20 }}
                    >
                        <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" vertical={false} />
                        <XAxis
                            dataKey="wavelength"
                            type="number"
                            domain={[minWavelength, maxWavelength]}
                            allowDataOverflow={true}
                            tick={{ fill: '#000000', fontSize: 12 }}
                            tickLine={false}
                            axisLine={{ stroke: '#000000' }}
                            label={{ value: 'Wavelength (nm)', position: 'insideBottom', offset: -10, fill: '#000000', fontSize: 12 }}
                        />
                        <YAxis hide domain={[0, 1.1]} />

                        <defs>
                            {fluorophores.map(dye => (
                                <linearGradient key={`grad_rep_${dye.id}`} id={`grad_rep_${dye.id}`} x1="0" y1="0" x2="0" y2="1">
                                    <stop offset="5%" stopColor={dye.color} stopOpacity={0.3} />
                                    <stop offset="95%" stopColor={dye.color} stopOpacity={0} />
                                </linearGradient>
                            ))}
                        </defs>

                        {/* Emission Primary */}
                        {fluorophores.map(dye => {
                            if (!dye.visible) return null;
                            return (
                                <Area
                                    key={`${dye.id}_em`}
                                    name={dye.name}
                                    type="monotone"
                                    dataKey={`${dye.id}_em`}
                                    stroke={dye.color}
                                    strokeWidth={2}
                                    fill={`url(#grad_rep_${dye.id})`}
                                    fillOpacity={0.4}
                                    dot={false}
                                    isAnimationActive={false}
                                />
                            );
                        })}

                        {/* Emission Secondary (Ghost for comparison) - Always show if Dual System */}
                        {isDual && fluorophores.map(dye => {
                            if (!dye.visible) return null;
                            return (
                                <Line
                                    key={`${dye.id}_em_secondary`}
                                    name={`${dye.name} (Reflection)`}
                                    type="monotone"
                                    dataKey={`${dye.id}_em_secondary`}
                                    stroke={dye.color}
                                    strokeWidth={1.5}
                                    strokeDasharray="4 2"
                                    strokeOpacity={0.5}
                                    dot={false}
                                    isAnimationActive={false}
                                />
                            );
                        })}

                        {/* Optics Lines (Dichroics) */}
                        {dichroics.map(optic => {
                            if (!optic.visible) return null;
                            return (
                                <Line
                                    key={optic.id}
                                    name={optic.name}
                                    type="monotone"
                                    dataKey={`${optic.id}_optic`}
                                    stroke={optic.color || '#9ca3af'}
                                    strokeWidth={1}
                                    strokeDasharray="4 4"
                                    dot={false}
                                    isAnimationActive={false}
                                />
                            );
                        })}

                        {/* Imaging Splitters */}
                        {imagingSplitters.map(splitter => {
                            if (!splitter.visible) return null;
                            return (
                                <Line
                                    key={splitter.id}
                                    name={splitter.name}
                                    type="monotone"
                                    dataKey={`${splitter.id}_splitter`}
                                    stroke="#3B82F6"
                                    strokeWidth={2}
                                    strokeDasharray="6 2"
                                    dot={false}
                                    isAnimationActive={false}
                                />
                            );
                        })}

                        {/* Filter Lines */}
                        <Line
                            name="Cam T Filter"
                            type="monotone"
                            dataKey="active_filter"
                            stroke="#FFD700"
                            strokeWidth={2}
                            strokeDasharray="5 5"
                            dot={false}
                            isAnimationActive={false}
                        />
                        {isDual && (
                            <Line
                                name="Cam R Filter"
                                type="monotone"
                                dataKey="secondary_filter"
                                stroke="#FFA500"
                                strokeWidth={2}
                                strokeDasharray="2 5"
                                dot={false}
                                isAnimationActive={false}
                            />
                        )}

                        <Legend
                            content={(props) => {
                                const { payload } = props;
                                return (
                                    <div className="flex flex-wrap justify-center gap-4 pt-4 text-xs">
                                        {payload?.map((entry, index) => {
                                            const value = entry.value || '';
                                            const isCamR = value.includes('(Reflection)');
                                            const isSplitter = value.includes('Splitter');
                                            const isFilter = value.includes('Filter');
                                            const isDichroic = value.includes('Dichroic') || (value && !isCamR && !isSplitter && !isFilter && !value.includes('(Em)'));

                                            // Determine border style based on type
                                            let borderStyle = 'solid';
                                            if (isCamR) borderStyle = 'dotted';
                                            if (isSplitter) borderStyle = 'dashed';

                                            // Clean up name for display
                                            let displayName = value;
                                            if (displayName.includes('(Em)')) displayName = displayName.replace('(Em)', '(Cam T)');
                                            if (displayName.includes('(Reflection)')) displayName = displayName.replace('(Reflection)', '(Cam R)');

                                            return (
                                                <div key={`item-${index}`} className="flex items-center gap-1.5">
                                                    <div
                                                        style={{
                                                            width: 12,
                                                            height: 12,
                                                            borderRadius: '50%',
                                                            border: `2px ${borderStyle} ${entry.color}`,
                                                            backgroundColor: 'transparent' // User asked for "outline", implies no fill or separate fill
                                                        }}
                                                    />
                                                    <span className="text-gray-700 font-medium">{displayName}</span>
                                                </div>
                                            );
                                        })}
                                    </div>
                                );
                            }}
                        />
                    </ComposedChart>
                </ResponsiveContainer>
            </div>

            {/* Efficiency Metrics Table */}
            <div className="mt-2">
                <h3 className="text-lg font-bold text-gray-900 mb-4">Detection Efficiency Metrics</h3>
                <table className="w-full text-left border-collapse">
                    <thead>
                        <tr className="border-b-2 border-gray-800">
                            <th className="py-2 font-bold text-gray-700">Fluorophore</th>
                            <th className="py-2 font-bold text-gray-700">Camera T (Transmission)</th>
                            {isDual && <th className="py-2 font-bold text-gray-700">Camera R (Reflection)</th>}
                            {isDual && <th className="py-2 font-bold text-gray-700">Total Efficiency</th>}
                            {isDual && <th className="py-2 font-bold text-gray-700">Split Ratio (T/Total)</th>}
                        </tr>
                    </thead>
                    <tbody>
                        {efficiencyMetrics.map((m, idx) => (
                            <tr key={idx} className="border-b border-gray-200">
                                <td className="py-3 flex items-center gap-2 font-medium">
                                    <span className="w-3 h-3 rounded-full" style={{ backgroundColor: m.color }}></span>
                                    {m.dyeName}
                                </td>
                                <td className="py-3 font-mono font-bold text-gray-800">{m.cam1}%</td>
                                {isDual && <td className="py-3 font-mono font-bold text-gray-800">{m.cam2 || '-'}%</td>}
                                {isDual && <td className="py-3 font-mono font-bold text-gray-900">
                                    {(parseFloat(m.cam1) + parseFloat(m.cam2 || '0')).toFixed(1)}%
                                </td>}
                                {isDual && <td className="py-3 font-mono text-gray-600">{m.splitRatio || '-'}%</td>}
                            </tr>
                        ))}
                        {efficiencyMetrics.length === 0 && (
                            <tr>
                                <td colSpan={4} className="py-4 text-center text-gray-400 italic">No active fluorophores selected.</td>
                            </tr>
                        )}
                    </tbody>
                </table>
            </div>

            {/* Footer */}
            <div className="mt-8 pt-4 border-t border-gray-200 text-center text-xs text-gray-400">
                www.abbelight-academy.com
            </div>
        </div>
    );
});

SpectraReport.displayName = 'SpectraReport';
